version: '3'
services:
  mevplus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    network_mode: host
    environment:
      - BUILDER_API_ADDRESS=
      - EXTERNAL_VALIDATOR_PROXY_ADDRESS=
      - ETH1_PRIVATE_KEY=
      - BEACON_NODE_URL=
      - EXECUTION_NODE_URL=
    restart: unless-stopped



